### ISSUE TITLE
what algorithm is used by function hff?

### ISSUE THREAD

**Issue by zzy5510** [MattiaMontanari/openGJK#27]
Hello! I have read your papers and codes, which are excellent works. I'm really interested about your work. I found there is an update in version3.0.0, where hff1 function is used to judge which Voronoi region is it belongs to. However, I found the algorithm used here is different from the way described on the paper 《Improving the GJK Algorithm for Faster and More Reliable Distance Queries Between Convex Objects》, which is the same as version 1.1. What kind of algorithm is used here?

Thank you again.

**Comment by MattiaMontanari** [comment]
@zzy5510 that's right! I'm very happy to know that someone dives so deep in the code.
The subalgorithm is indeed different - this is much better - however the theory is not published anywhere simply because I never had time to wrap up the paper..

**Comment by bruyeret** [comment]
Hello, I was surprised to see that the algorithm didn't use signed volumes 😀 
Is there somewhere in the repo where the algorithm is explained in broad terms?
The paper about signed volumes explained that it was a very robust method, is it still the case with the new algorithm?
For example I see that the barycentric coordinates are computed using a matrix T of dot products instead of a matrix M of projected coordinates

**Comment by MattiaMontanari** [comment]
@bruyeret there is nothing published on the new method. The little time I can dedicate to this project now focuses on speed. Compared to the signed volumes paper the new method is faster, fixes some bugs and - as far as my benchmarks go - equally robust.

Do you face any issue or have any question on the library?

**Comment by bruyeret** [comment]
As I didn't find any documentation on the algorithm, I retro-engineered it and I think that I understood everything.
If I have any question, I will open an issue, thanks!
